apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fbuo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fqcd-tenant/rhtap-demo-app/hacbs-test-project-fbuo@sha256:f768b0d950ef58543dbc34a28cdeda1d7056affc9ff7d12b4bb53632ff312803
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
